# Generated by Django 4.1 on 2022-08-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associedCards', models.TextField(max_length=300)),
                ('associedCardRefs', models.TextField(max_length=300)),
                ('assets', models.TextField(max_length=300)),
                ('regions', models.CharField(max_length=300)),
                ('regionRefs', models.CharField(max_length=300)),
                ('attack', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('health', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
                ('descriptionRaw', models.TextField(max_length=300)),
                ('levelupDescription', models.TextField(max_length=300)),
                ('levelupDescriptionRaw', models.TextField(max_length=300)),
                ('flavorText', models.TextField(max_length=300)),
                ('artistName', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('cardCode', models.CharField(max_length=300)),
                ('keywords', models.CharField(max_length=300)),
                ('keywordRefs', models.CharField(max_length=300)),
                ('spellSpeed', models.CharField(max_length=300)),
                ('spellSpeedRefs', models.CharField(max_length=300)),
                ('rarity', models.CharField(max_length=300)),
                ('subytypes', models.CharField(max_length=300)),
                ('supertype', models.CharField(max_length=300)),
                ('cardType', models.CharField(max_length=300)),
                ('collectible', models.BooleanField(default=True)),
                ('collectionSet', models.CharField(max_length=300)),
            ],
        ),
    ]
