# Generated by Django 4.1 on 2022-08-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
