# Generated by Django 4.1 on 2022-08-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartas', '0002_delete_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set1',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('associatedcards', models.JSONField(blank=True, db_column='associatedCards', null=True)),
                ('associatedcardrefs', models.JSONField(blank=True, db_column='associatedCardRefs', null=True)),
                ('assets', models.JSONField(blank=True, null=True)),
                ('regions', models.JSONField(blank=True, null=True)),
                ('regionrefs', models.JSONField(blank=True, db_column='regionRefs', null=True)),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('health', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('descriptionraw', models.TextField(blank=True, db_column='descriptionRaw', null=True)),
                ('levelupdescription', models.TextField(blank=True, db_column='levelupDescription', null=True)),
                ('levelupdescriptionraw', models.TextField(blank=True, db_column='levelupDescriptionRaw', null=True)),
                ('flavortext', models.TextField(blank=True, db_column='flavorText', null=True)),
                ('artistname', models.TextField(blank=True, db_column='artistName', null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('cardcode', models.TextField(blank=True, db_column='cardCode', null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('keywordrefs', models.JSONField(blank=True, db_column='keywordRefs', null=True)),
                ('spellspeed', models.TextField(blank=True, db_column='spellSpeed', null=True)),
                ('spellspeedref', models.TextField(blank=True, db_column='spellSpeedRef', null=True)),
                ('rarity', models.TextField(blank=True, null=True)),
                ('rarityref', models.TextField(blank=True, db_column='rarityRef', null=True)),
                ('subtypes', models.JSONField(blank=True, null=True)),
                ('supertype', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('collectible', models.TextField(blank=True, null=True)),
                ('set', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'set1',
                'managed': False,
            },
        ),
    ]
